"""empty message

Revision ID: 006cde4f66c9
Revises: 898439852975
Create Date: 2023-12-14 05:31:30.118975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006cde4f66c9'
down_revision = '898439852975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gf', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('recipe_parent_id_fkey', type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('gluten_free')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gluten_free', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('recipe_parent_id_fkey', 'recipe', ['parent_id'], ['id'])
        batch_op.drop_column('private')
        batch_op.drop_column('gf')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
