"""empty message

Revision ID: 100ba65b5c3f
Revises: 006cde4f66c9
Create Date: 2023-12-14 06:41:19.650583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100ba65b5c3f'
down_revision = '006cde4f66c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
