"""empty message

Revision ID: 898439852975
Revises: 67f6b05b9b9f
Create Date: 2023-12-13 23:24:53.547231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898439852975'
down_revision = '67f6b05b9b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
