"""empty message

Revision ID: aebd19eb1d23
Revises: 9f79246c4d2b
Create Date: 2023-12-14 19:58:35.107221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aebd19eb1d23'
down_revision = '9f79246c4d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_id', sa.Integer(), nullable=True))
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('child_id')

    # ### end Alembic commands ###
