"""empty message

Revision ID: f20337cb527e
Revises: aebd19eb1d23
Create Date: 2023-12-15 14:19:06.352764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f20337cb527e'
down_revision = 'aebd19eb1d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collab_id', sa.Integer(), nullable=True))
        batch_op.drop_column('editors')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editors', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
        batch_op.drop_column('collab_id')

    # ### end Alembic commands ###
